# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: translate.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'translate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftranslate.proto\x12\ttranslate\"5\n\x10TranslateRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x13\n\x0btarget_lang\x18\x02 \x01(\t\")\n\x0eTranslateReply\x12\x17\n\x0ftranslated_text\x18\x01 \x01(\t2]\n\x12TranslationService\x12G\n\rTranslateText\x12\x1b.translate.TranslateRequest\x1a\x19.translate.TranslateReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'translate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSLATEREQUEST']._serialized_start=30
  _globals['_TRANSLATEREQUEST']._serialized_end=83
  _globals['_TRANSLATEREPLY']._serialized_start=85
  _globals['_TRANSLATEREPLY']._serialized_end=126
  _globals['_TRANSLATIONSERVICE']._serialized_start=128
  _globals['_TRANSLATIONSERVICE']._serialized_end=221
# @@protoc_insertion_point(module_scope)
