# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tts.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'tts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttts.proto\x12\x03tts\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\" \n\nAudioReply\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x32?\n\nTTSService\x12\x31\n\x0cTextToSpeech\x12\x10.tts.TextRequest\x1a\x0f.tts.AudioReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTREQUEST']._serialized_start=18
  _globals['_TEXTREQUEST']._serialized_end=45
  _globals['_AUDIOREPLY']._serialized_start=47
  _globals['_AUDIOREPLY']._serialized_end=79
  _globals['_TTSSERVICE']._serialized_start=81
  _globals['_TTSSERVICE']._serialized_end=144
# @@protoc_insertion_point(module_scope)
